# Generated by Django 5.1.4 on 2025-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
